_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 7487212d-6aae-44a7-9518-2cc589168301
name: 'Innoraft Ecommerce Website'
mail: sayan.dutta@innoraft.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/13
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
